version: '3.2'
services:
  trusted:
    build: ./Trusted
    ports:
      - "4000:80"
    ipc:
      "shareable"
    volumes:
      - type: "tmpf"
        target: tmp:/tmp
  untrusted:
    build: ./Untrusted
    deploy:
      replicas: 5
    volumes:
      - type: "tmpf"
        target: tmp:/tmp
    cap_drop:
      - ALL
volumes:
  tmp:
