version: '3.5'
services:
  trusted:
    build: 
      context: ./Trusted
      shm_size: '300 mb'
    shm_size: '300 mb'
    ports:
      - "4000:80"
    ipc:
      "shareable"
    volumes:
      - tmp:/tmp
  untrusted:
    build: ./Untrusted
    deploy:
      replicas: 5
    volumes:
      - tmp:/tmp
    cap_drop:
      - SETPCAP
      - MKNOD
      - AUDIT_WRITE
      - CHOWN
      - NET_RAW
      - DAC_OVERRIDE
      - FOWNER
      - KILL
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
volumes:
  tmp:
