version: '3.5'
services:
  trusted:
    image: dcb22/trusted
    build: 
      context: ./Trusted
      shm_size: '300 mb'
    deploy:
      restart_policy: 
        condition: on-failure
    shm_size: '300 mb'
    ports:
      - "4000:80"
    ipc:
      "shareable"
    volumes:
      - tmp:/tmp
  untrusted:
    image: dcb22/untrusted
    build: ./Untrusted
    deploy:
      replicas: 5
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 100M
    volumes:
      - tmp:/tmp
    cap_drop:
      - SETPCAP
      - MKNOD
      - AUDIT_WRITE
      - CHOWN
      - NET_RAW
      - DAC_OVERRIDE
      - FOWNER
      - KILL
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
volumes:
  tmp:
