version: '3.2'
services:
  trusted:
    build: ./Trusted
    ports:
      - "4000:80"
    ipc:
      "shareable"
    volumes:
      - type: "tmpf"
        target: tmp:/tmp
  untrusted:
    build: ./Untrusted
    deploy:
      replicas: 5
    volumes:
      - type: "tmpf"
        target: tmp:/tmp
    cap_drop:
      - SETPCAP
      - MKNOD
      - AUDIT_WRITE
      - CHOWN
      - NET_RAW
      - DAC_OVERRIDE
      - FOWNER
      - KILL
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
volumes:
  tmp:
