# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import codeRunner_pb2 as codeRunner__pb2


class codeRunnerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.runCode = channel.unary_unary(
        '/codeRunner/runCode',
        request_serializer=codeRunner__pb2.code.SerializeToString,
        response_deserializer=codeRunner__pb2.id_.FromString,
        )


class codeRunnerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def runCode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_codeRunnerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'runCode': grpc.unary_unary_rpc_method_handler(
          servicer.runCode,
          request_deserializer=codeRunner__pb2.code.FromString,
          response_serializer=codeRunner__pb2.id_.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'codeRunner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
