# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: codeRunner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='codeRunner.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x63odeRunner.proto\"\"\n\x04\x63ode\x12\r\n\x05toRun\x18\x01 \x02(\t\x12\x0b\n\x03id_\x18\x02 \x02(\t\"\x12\n\x03id_\x12\x0b\n\x03id_\x18\x01 \x02(\t2&\n\ncodeRunner\x12\x18\n\x07runCode\x12\x05.code\x1a\x04.id_\"\x00')
)




_CODE = _descriptor.Descriptor(
  name='code',
  full_name='code',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='toRun', full_name='code.toRun', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_', full_name='code.id_', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=54,
)


_ID_ = _descriptor.Descriptor(
  name='id_',
  full_name='id_',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_', full_name='id_.id_', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['code'] = _CODE
DESCRIPTOR.message_types_by_name['id_'] = _ID_
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

code = _reflection.GeneratedProtocolMessageType('code', (_message.Message,), dict(
  DESCRIPTOR = _CODE,
  __module__ = 'codeRunner_pb2'
  # @@protoc_insertion_point(class_scope:code)
  ))
_sym_db.RegisterMessage(code)

id_ = _reflection.GeneratedProtocolMessageType('id_', (_message.Message,), dict(
  DESCRIPTOR = _ID_,
  __module__ = 'codeRunner_pb2'
  # @@protoc_insertion_point(class_scope:id_)
  ))
_sym_db.RegisterMessage(id_)



_CODERUNNER = _descriptor.ServiceDescriptor(
  name='codeRunner',
  full_name='codeRunner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=76,
  serialized_end=114,
  methods=[
  _descriptor.MethodDescriptor(
    name='runCode',
    full_name='codeRunner.runCode',
    index=0,
    containing_service=None,
    input_type=_CODE,
    output_type=_ID_,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CODERUNNER)

DESCRIPTOR.services_by_name['codeRunner'] = _CODERUNNER

# @@protoc_insertion_point(module_scope)
